CREATE TYPE event_type AS ENUM (
  'Music Performance',
  'Art Show',
  'Dance Performance',
  'Book Signing',
  'Craft Fair',
  'Poetry Reading',
  'Fashion Show',
  'Other'
);

CREATE TABLE events (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  location TEXT NOT NULL,
  city TEXT,
  state TEXT,
  slots_available INTEGER NOT NULL,
  host_id INTEGER REFERENCES users(id) on DELETE CASCADE NOT NULL,
  event_type event_type DEFAULT 'Other',
  paid BOOLEAN DEFAULT FALSE,
  description TEXT,
  additional_details TEXT,
  img_url TEXT DEFAULT NULL,
  archived BOOLEAN DEFAULT 'false'
);