CREATE TYPE status AS ENUM(
  'Accepted',
  'Denied',
  'Pending'
);

CREATE TABLE requestors (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  booking_status status DEFAULT 'Pending'
);